clipper @rac  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rrnt  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rrnt1  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rrnt2  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rres  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rccp  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rinv  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rmkt  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rdyp  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rrpt  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper @rsys  -l -o..\OBJ
            if errorlevel 1 goto exit 
clipper rafunc  -l -o..\OBJ
            if errorlevel 1 goto exit 
 clipper rafunc1  -l -o..\OBJ
             if errorlevel 1 goto exit 
 clipper rafunc2  -l -o..\OBJ
             if errorlevel 1 goto exit 
 clipper rafunc3  -l -o..\OBJ
             if errorlevel 1 goto exit 
 clipper rafunc4  -l -o..\OBJ
             if errorlevel 1 goto exit 
 clipper alterror  -l -o..\OBJ
             if errorlevel 1 goto exit 
:EXIT
